### ISSUE TITLE
conventionalcommits presets with 7.x releases

### ISSUE THREAD

**Issue by wyardley** [conventional-changelog/conventional-changelog#1109]
Hi - since the update to 7.0.1 (7.0.0 also broke with the missing constants), I'm seeing semantic-release "succeed" without actually cutting a release with our existing configuration (see below).

Is this related to the following breaking change, and if so, is there more information or a doc that explains this a bit more?

> Now all presets are exports preset config factory function. conventional-changelog-preset-loader now exports new loadPreset and createPresetLoader functions. If you are using presets indirectly, using preset name, no any changes in configuration needed, just upgrade packages to latest versions.

Am I misunderstanding what indirect preset usage would look like?

My `.releaserc.yaml`:

```yaml
branches:
  - main
  - name: beta
    prerelease: true
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - - '@semantic-release/changelog'
    - preset: conventionalcommits
  - '@semantic-release/npm'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - package.json
        - package-lock.json
  - - '@semantic-release/github'
    - assets:
        - CHANGELOG.md
        - package.json
```

specifically, here's a run. this exits 0 / succeeds (same with a dry-run), but never seems to 

```
[9:31:06 PM] [semantic-release] › ℹ  Running semantic-release version 21.1.1
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[9:31:06 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[9:31:19 PM] [semantic-release] › ✔  Run automated release from branch main on repository xxx
[9:31:19 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:31:19 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[9:31:19 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[9:31:19 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[9:31:19 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://npm.pkg.github.com/
[9:31:19 PM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /home/circleci/.npmrc
[9:31:19 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[9:31:19 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[9:31:19 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[9:31:19 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[9:31:19 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[9:31:19 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[9:31:19 PM] [semantic-release] › ℹ  Found git tag v7.0.1 associated with version 7.0.1 on branch main
[9:31:19 PM] [semantic-release] › ℹ  Found 5 commits since last release
[9:31:19 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
```

but never gets further like in a normal run:
```
[9:45:25 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #1198 from xxx/xyz
```
